# Generated by Django 4.2.16 on 2024-11-14 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_overview', models.TextField()),
                ('is_adult', models.BooleanField()),
                ('movie_popularity', models.FloatField()),
                ('movie_rating', models.FloatField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=200)),
                ('bookmarks', models.ManyToManyField(related_name='bookmarked_movies', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
