# Generated by Django 4.2.16 on 2024-11-16 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('adult', models.BooleanField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=200)),
                ('genre_ids', models.ManyToManyField(to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('adult', models.BooleanField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre_ids', models.ManyToManyField(to='movies.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movies_like',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('adult', models.BooleanField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre_ids', models.ManyToManyField(to='movies.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movies_bookmark',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'id'), name='unique_user_movie_like'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'id'), name='unique_user_movie_bookmark'),
        ),
    ]
